import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import AttributeProviders from "./providers/AttributeProviders";

//폰트 주입 샘플
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

//메타데이터 샘플
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//next-themes next-themes next-themes 해보기!
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} text-[#119595] dark:bg-gray-900 text-black dark:text-white`}
      >
        <AttributeProviders>{children}</AttributeProviders>
      </body>
    </html>
  );
}
