import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import AttributeProviders from "./providers/AttributeProviders";

//폰트 주입 샘플
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

//메타데이터 샘플
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} text-[#119595]`}>
        <AttributeProviders>{children}</AttributeProviders>
      </body>
    </html>
  );
}
